config/routes.rb
Rails.application.routes.draw do  

  
  get '/msg' => 'welcome#send_msg'#, :as => 'send_msg'
  post '/msg' => 'welcome#send_msg', :as => 'send_msg'

  

  

end

app/models/user.rb
class User < ActiveRecord::Base

  #has_one :custom_user_detail

  validates :email, uniqueness: true
  
  attr_accessor :password, :password_confirmation, :phone_tmp_token
  #attr_accessible :password, :email, :password_hash, :password_salt, :secret_token, :kyc_secret_token, :is_admin
  
  before_create :encrypt_password  
  before_create :generate_token

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      #session[:user_id] = user.id      
      user
    else
      nil
    end
  end

  def encrypt_password
    require 'securerandom'      
    if self.password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
      #self.kyc_secret_token = SecureRandom.hex(10)              
      self.secret_token = SecureRandom.hex(10)      
    end
  end
  def generate_token
     require 'securerandom'    
     self.phone_no_token = SecureRandom.hex(3) 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  	#flash[:notice] = "Back user singed in successfully."
    #redirect_to admin_campaigns_url, flash: flash  
  end

  def register
  end

  def send_msg
  	if request.post?
  	  number = '+91'+params[:mobile_no]
  	  message = params[:msg_text]	
  	  send_sms(number, message)
  	end
  end

  def send_sms(number, message)
    require 'rubygems'
    require 'twilio-ruby'

    number = number
    message = message

    #RKP
    account_sid = "AC8e35e4fcb6df2236af1e530492c8e484"
    auth_token = "267edd5927beed7e5a33ab7dc6cc636e"
    #RKP

    @client = Twilio::REST::Client.new account_sid, auth_token    
    @message = @client.account.messages.create({:to => "#{number}",    
    :from => "+19123302888", 
    :body => "MSG by Anil:- #{message}"})       
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container text-center">
    <a href="#"><img src="assets/images/logo-dark.png" alt=""></a>
    <ul class="list-inline socials">
      <li><a href="#" class="fb"><i class="ion-social-facebook-outline"></i></a></li>
      <li><a href="#" class="twit"><i class="ion-social-twitter-outline"></i></a></li>
      <li><a href="#" class="g-plus"><i class="ion-social-googleplus-outline"></i></a></li>
      <li><a href="#" class="yout"><i class="ion-social-youtube-outline"></i></a></li>
      <li><a href="#" class="drib"><i class="ion-social-dribbble-outline"></i></a></li>
    </ul>
    <p>&copy; 2014. Made with <i class="ion-ios-heart-outline"></i> by Trigmasoft</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="w-nav navbar" data-collapse="medium" data-animation="default" data-duration="400" data-contain="1" data-ix="show-navbar-on-load">
  <div class="w-container navbar-container">
    <a class="w-nav-brand logo-container" href="/">
      <h2 class="logo">Buneyard Compagnie</h2>
    </a>
    <nav class="w-nav-menu nav-link-container" role="navigation">
      <a class="w-nav-link nav-link" href="#Home">Home</a>
      <a class="w-nav-link nav-link" href="#About">About</a>
      <a class="w-nav-link nav-link" href="#Process">Our Process</a>
      <a class="w-nav-link nav-link" href="#Features">Features &amp; benefits</a>
      <a class="w-nav-link nav-link" href="#Offering">coffee offering</a>
      <!-- <a class="w-nav-link nav-link" href="#Register">register</a> -->
      <% if current_user %>
        <a class="w-nav-link nav-link" href="<%= "/user-profile-page/#{current_user.secret_token}" %>"><%= current_user.first_name %></a>
      <% else %>
        <a class="w-nav-link nav-link" href="/register">register</a>
      <% end %>  
    </nav>
    <div class="w-nav-button menu-button">
      <div class="w-icon-nav-menu menu-icon"></div>
    </div>
  </div>
</div>
<% if flash[:notice].present? %>
<%= js add_gritter(flash[:notice])  %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trigmasoft</title>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Montserrat:400,700', 'http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,400,300,600,700', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body data-spy="scroll" data-target=".navbar" data-offset="80">
<%#= render 'layouts/header' %>
<%= yield %>
<%#= render 'layouts/footer' %>
</body>
</html>

app/views/welcome/send_msg.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Trigmasoft-Send Msg</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <h2>Trigmasoft-Send Msg</h2>
  <%= form_tag send_msg_path do %>
    <div class="form-group">
      <label for="email">Mobile No:</label>    
      <%= text_field_tag 'mobile_no', nil, :placeholder => "Enter mobile no.", class: "form-control" %>  
    </div>
    <div class="form-group">
      <label for="pwd">Msg Text:</label>
      <%= text_area_tag 'msg_text', nil, :placeholder => "Enter msg text", class: "form-control" %>
    </div>
        
    <button type="submit" class="btn btn-primary">Send</button>
  <% end %> 
</div>

</body>
</html>